# .github/workflows/hello-world.yml

name: Hello World Workflow
run-name: Workflow running from ${{ github.ref_name }} branch

# This enables the workflow to be triggered manually via the API or GitHub UI
on:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello World
        run: echo "Hello, World!"
