name: PR Failure Summary

on:
  push:
    branches:
      - main  # Specify the branch for push events
  pull_request:
    types: [opened, synchronize, reopened]  # Trigger on PR events

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - name: Summary
        run: echo "Summary"

      - name: Test1
        run: echo "Test1"

      - name: Test2
        run: false  # This will fail

      - name: Test3
        if: always()
        run: echo "Test3"

      - name: Test4
        if: always()
        run: echo "Test4"

      - name: PR Summary Comment
        if: github.event_name == 'pull_request'  # Only run for PR events
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = github.context.payload.pull_request.number;

            // Check step results from the workflow
            const results = {
              Test2: 'failed',
              Test3: 'passed',
              Test4: 'passed',
            };

            // Create a comment summarizing the results
            const comment = `### Workflow Summary\n
            - **Test1**: passed\n
            - **Test2**: ${results.Test2}\n
            - **Test3**: ${results.Test3}\n
            - **Test4**: ${results.Test4}\n`;

            // Create the comment on the PR
            await github.issues.createComment({
              ...github.context.repo,
              issue_number: prNumber,
              body: comment,
            });
