name: Multi-Job PR Failure Summary

on:
  push

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Get PR Number
        run: |
          PR_NUMBER=$(gh pr view --json number --jq .number || echo "")
          PR_TITLE=$(gh pr view --json title --jq .title || echo "")
          echo "PR_NUMBER=$PR_NUMBER"
          echo "PR_TITLE=$PR_TITLE"
        env:
          GH_TOKEN: ${{ github.GITHUB_TOKEN }}
      - name: Test1
        id: test1
        run: false
      - name: Test2
        if: success() || failure()
        continue-on-error: true
        id: test2
        run: false  # This will fail
      - name: Test3
        if: success() || failure()
        continue-on-error: true
        id: test3
        run: echo "Test3"
