name: PR Information Workflow

on:
  push

jobs:
  job1:
    name: Test 1
    runs-on: ubuntu-latest
    outputs:
      test1_conclusion: ${{ steps.test1.conclusion }}  # Correct output property
      test2_conclusion: ${{ steps.test2.conclusion }}  # Correct output property
    steps:
      - name: test1
        if: success() || failure()  # Ensure this step runs regardless of success or failure
        id: test1
        run: exit 1  # Simulate failure for test1

      - name: test2
        if: success() || failure()  # Ensure this step runs regardless of test1 result
        id: test2
        run: exit 0  # Simulate success for test2

  job2:
    name: Test 2
    needs: [job1]
    if: ${{ needs.job1.outputs.test2_conclusion == 'success' }}  # Correct the output to use 'conclusion'
    runs-on: ubuntu-latest
    steps:
      - name: test3
        run: echo "Running test3 because test2 from job1 passed!"
