name: PR Information Workflow

on:
  push

jobs:
  job1:
    name: Test 1
    runs-on: ubuntu-latest
    outputs:
      test1: ${{ steps.test1.conclusion }}
    steps:
      - name: test1
        if: success() || failure()
        id: test1
        run: false
        
  job2:
    name: Test 2
    needs: [job1]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check job1 outcome and issue warning if failed
        run: |
          if [ "${{ needs.job1.outputs.test1 }}" == "failure" ]; then
            echo "::warning::job1 failed, proceeding with job2."
          else
            echo "job1 succeeded."
          fi
      - name: test2
        run: true
