name: Multi-Job PR Failure Summary

on:
  push

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Test1
        id: test1
        run: false
      - name: Test2
        id: test2
        run: false  # This will fail
      - name: Test3
        id: test3
        run: echo "Test3"
