name: PR Failure Summary

on:
  workflow_dispatch:


jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - name: Summary
        run: echo "Summary"

      - name: Test1
        run: echo "Test1"

      - name: Test2
        run: false
      
      - name: Test3
        run: echo "Test3"