name: Multi-Job PR Failure Summary

on:
  push

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Number
        run: |
          echo "PR Number: ${{ github.event.number }}"
          echo "PR Name: ${{ github.event.pull_request.number }}"
      - name: Test1
        id: test1
        run: false
      - name: Test2
        if: success() || failure()
        continue-on-error: true
        id: test2
        run: false  # This will fail
      - name: Test3
        if: success() || failure()
        continue-on-error: true
        id: test3
        run: echo "Test3"
  job2:
    name: Job 2
    needs: job1
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Test4
        if: success() || failure()
        id: test4
        run: echo "Test4"
