name: PR Information Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  job1:
    name: Get PR Information
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get PR Number and Title
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}"
          echo "PR_TITLE=${{ github.event.pull_request.title }}"

      - name: Test1
        id: test1
        run: false
      - name: Test2
        if: success() || failure()
        continue-on-error: true
        id: test2
        run: false  # This will fail
      - name: Test3
        if: success() || failure()
        continue-on-error: true
        id: test3
        run: echo "Test3"
