name: PR Information Workflow

on:
  push
  

jobs:
  job1:
    name: Test 1
    runs-on: ubuntu-latest
    steps:
      - name: test1
        run: false
  job2:
    name: Test 2
    runs-on: ubuntu-latest
    steps:
      - name: test2
        run: true
