name: PR Failure Summary

on:
  push

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - name: Summary
        run: echo "Summary"

      - name: Test1
        run: echo "Test1"

      - name: Test2
        run: false
      
      - name: Test3
        if: always()
        run: echo "Test3"

      - name: Test4
        run: echo "Test4"