name: PR Information Workflow

on:
  push

jobs:
  job1:
    name: Test 1
    runs-on: ubuntu-latest
    if: success() || failure()
    outputs:
      test1: ${{ steps.test1.conclusion }}
    steps:
      - name: test1
        id: test1
        run: false
  job2:
    name: Test 2
    needs: [job1] 
    runs-on: ubuntu-latest
    steps:
      - name: test2
        run: true
