name: PR Information Workflow

on:
  workflow_dispatch:
  

jobs:
  job1:
    name: Get PR Information
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get PR Number and Title
        run: |
          gh pr view --json number --jq '.number'
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
